name: Release Candidate

on:
  pull_request:
    branches:
      - 'release/**'

jobs:
  tag:
    name: Tag Release Candidate
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            set-safe-directory: '*'
        - name: Get Version
          id: version
          run: |
            V="${GITHUB_REF#refs/heads/release/v}"
            echo "version=${V}" >> $GITHUB_OUTPUT
        - name: Create Tag
          run: |
            #TODO: auto increment versions
            V="v${{steps.version.outputs.version}}_1"
            git tag "$V" -m "Release Candidate $V"
            git push "$V"
